typescript:
  - changed-files:
      - any-glob-to-any-file: src/**
action-config:
  - changed-files:
      - any-glob-to-any-file: action.yml
enhancement:
  - head-branch:
      - ^feat(ure)?/
bugfix:
  - head-branch:
      - ^bug(fix)?/
refactor:
  - head-branch:
      - ^refactor?/
