name-template: $RESOlVED_VERSION released
tag-template: $RESOVED_VERSION
categories:
  - title: Features
    labels:
      - feature
      - enhancement
  - title: Bug Fixes
    labels:
      - bugfix
  - title: Maintenance / Refactors
    labels:
      - chore
      - refactor
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## What's changed
  
  $CHANGES