name-template: $RESOLVED_VERSION released
tag-template: $RESOVED_VERSION
categories:
  - title: Features
    labels:
      - enhancement
  - title: Bug Fixes
    labels:
      - bug
  - title: Maintenance / Refactors
    labels:
      - chore
      - refactor
version-resolver:
  major:
    labels:
      - breaking-change
  minor:
    labels:
      - enhancement
  patch:
    labels:
      - patch
  default: patch
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## What's changed
  
  $CHANGES