"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.prefixComment = void 0;
exports.parseCheckList = parseCheckList;
exports.renderCheckList = renderCheckList;
const headingPrefix = "#### ";
const checkedPrefix = "- [x] ";
const uncheckedPrefix = "- [ ] ";
exports.prefixComment = "<!-- Generated by kasaikou/self-review-checklist-actions, DO NOT EDIT. -->";
function parseCheckList(markdown) {
    const lines = markdown.split('\n');
    let currentLabel = "";
    let resultMap = new Map();
    for (const line of lines) {
        if (line.startsWith(headingPrefix)) {
            currentLabel = line.slice(headingPrefix.length);
        }
        else if (line.startsWith(checkedPrefix)) {
            let todoMap = resultMap.get(currentLabel);
            todoMap.set(line.slice(checkedPrefix.length), true);
            resultMap.set(currentLabel, todoMap);
        }
        else if (line.startsWith(uncheckedPrefix)) {
            let todoMap = resultMap.get(currentLabel);
            todoMap.set(line.slice(uncheckedPrefix.length), false);
            resultMap.set(currentLabel, todoMap);
        }
    }
    return resultMap;
}
function renderCheckList(input) {
    let markdown = "";
    markdown += exports.prefixComment + "\n\n";
    for (const content of input.contents) {
        markdown += headingPrefix + content.label + "\n\n";
        for (const checkbox of content.list) {
            markdown += (checkbox.checked ? checkedPrefix : uncheckedPrefix) + checkbox.name + "\n";
        }
        markdown += "\n";
    }
    return markdown;
}
