on:
  pull_request:
    types: [opened, synchronize]
jobs:
  run:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
